// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzbtkaltmqlvautvdrsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6YnRrYWx0bXFsdmF1dHZkcnNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0ODU1NzUsImV4cCI6MjA1ODA2MTU3NX0.X8TiUuupNWKG1rWWgSRUkqCvKOwkvSRZMdcd3L4F88g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);