// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://lyxhxlvshcsvoqdicqhm.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5eGh4bHZzaGNzdm9xZGljcWhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDY3ODAsImV4cCI6MjA1ODEyMjc4MH0.pV26CUDC1Igsr2lKOB3AKGT3bAsqAB20YEw8PTyAzBU';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
);
